import oclif from 'eslint-config-oclif';

export default [
  {ignores: ['lib/**', 'tmp/**', 'docs/**', 'dist/**', '**/*.bundle.js', '**/*.html']},
  ...oclif,
  {
    rules: {
      // Project uses 2-space indent
      '@stylistic/indent': ['error', 2, {SwitchCase: 1}],
      '@stylistic/object-curly-spacing': ['error', 'never'],
      'semi': ['error', 'always'],
      // CommonJS project — no .js extension on imports
      'n/file-extension-in-import': 'off',
      // Type import style unchanged
      '@typescript-eslint/consistent-type-imports': 'off',
      // Existing code uses 'as' casts and any types
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      // Disable all perfectionist sorting rules
      'perfectionist/sort-classes': 'off',
      'perfectionist/sort-imports': 'off',
      'perfectionist/sort-named-imports': 'off',
      'perfectionist/sort-objects': 'off',
      'perfectionist/sort-array-includes': 'off',
      'perfectionist/sort-interfaces': 'off',
      'perfectionist/sort-enums': 'off',
      'perfectionist/sort-union-types': 'off',
      'perfectionist/sort-exports': 'off',
      'perfectionist/sort-maps': 'off',
      'perfectionist/sort-switch-case': 'off',
      // Disable all unicorn rules (opinionated, not in original config)
      'unicorn/prefer-early-return': 'off',
      'unicorn/no-array-reduce': 'off',
      'unicorn/no-array-for-each': 'off',
      'unicorn/prevent-abbreviations': 'off',
      'unicorn/no-useless-undefined': 'off',
      'unicorn/prefer-ternary': 'off',
      'unicorn/no-nested-ternary': 'off',
      'unicorn/prefer-module': 'off',
      'unicorn/no-process-exit': 'off',
      'unicorn/import-style': 'off',
      'unicorn/prefer-node-protocol': 'off',
      'unicorn/prefer-date-now': 'off',
      'unicorn/consistent-boolean-name': 'off',
      'unicorn/prefer-array-some': 'off',
      'unicorn/no-array-callback-reference': 'off',
      'unicorn/prefer-string-slice': 'off',
      'unicorn/prefer-spread': 'off',
      'unicorn/prefer-array-flat': 'off',
      'unicorn/no-lonely-if': 'off',
      'unicorn/no-negated-condition': 'off',
      'unicorn/catch-error-name': 'off',
      'unicorn/prefer-logical-operator-over-ternary': 'off',
      'unicorn/prefer-at': 'off',
      'unicorn/prefer-array-index-of': 'off',
      'unicorn/prefer-number-properties': 'off',
      'unicorn/no-for-loop': 'off',
      'unicorn/prefer-set-has': 'off',
      'unicorn/prefer-regexp-test': 'off',
      'unicorn/no-object-constructor-with-argument': 'off',
      'unicorn/explicit-length-check': 'off',
      'unicorn/prefer-includes': 'off',
      'unicorn/consistent-function-scoping': 'off',
      // Disable all jsdoc rules (project doesn't use jsdoc)
      'jsdoc/require-jsdoc': 'off',
      'jsdoc/require-param': 'off',
      'jsdoc/require-returns': 'off',
      'jsdoc/require-param-description': 'off',
      'jsdoc/require-returns-description': 'off',
      'jsdoc/tag-lines': 'off',
      'jsdoc/check-tag-names': 'off',
      'jsdoc/require-yields': 'off',
      // Keep other rules from original config
      'require-unicode-regexp': 'off',
      'n/no-unsupported-features/node-builtins': 'off',
      '@stylistic/padding-line-between-statements': 'off',
      '@stylistic/operator-linebreak': 'off',
      'arrow-body-style': 'off',
      'no-promise-executor-return': 'off',
      '@typescript-eslint/no-confusing-void-expression': 'off',
      '@typescript-eslint/prefer-promise-reject-errors': 'off',
      '@typescript-eslint/no-shadow': 'off',
      '@typescript-eslint/prefer-regexp-exec': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/no-restricted-types': 'off',
      'n/prefer-global/buffer': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/promise-function-async': 'off',
      'import-x/no-cycle': 'off',
      'import-x/no-duplicates': 'off',
      // More unicorn rules in existing code
      'unicorn/prefer-string-replace-all': 'off',
      'unicorn/switch-case-braces': 'off',
      'unicorn/no-for-each': 'off',
      'unicorn/no-useless-fallback-in-spread': 'off',
      'unicorn/prefer-split-limit': 'off',
      'unicorn/prefer-smaller-scope': 'off',
      'unicorn/no-useless-switch-case': 'off',
      'unicorn/prefer-includes-over-repeated-comparisons': 'off',
      'unicorn/prefer-object-iterable-methods': 'off',
      'unicorn/prefer-number-coercion': 'off',
      'unicorn/prefer-unicode-code-point-escapes': 'off',
      // More @typescript-eslint rules not in original config
      '@typescript-eslint/consistent-type-definitions': 'off',
      '@typescript-eslint/consistent-type-exports': 'off',
      '@typescript-eslint/class-literal-property-style': 'off',
      '@typescript-eslint/prefer-optional-chain': 'off',
      '@typescript-eslint/switch-exhaustiveness-check': 'off',
      '@typescript-eslint/no-unnecessary-type-arguments': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      // Other style rules
      '@stylistic/arrow-parens': 'off',
      'prefer-destructuring': 'off',
      'func-names': 'off',
      // Additional unicorn rules in existing code
      'unicorn/no-computed-property-existence-check': 'off',
      'unicorn/empty-brace-spaces': 'off',
      'unicorn/logical-assignment-operators': 'off',
      'unicorn/no-unsafe-string-replacement': 'off',
      // Style formatting rules — keep existing code unchanged
      '@stylistic/object-curly-newline': 'off',
      '@stylistic/comma-dangle': 'off',
      'object-shorthand': 'off',
      // Type safety rules requiring code changes
      '@typescript-eslint/restrict-plus-operands': 'off',
      '@typescript-eslint/no-unnecessary-type-conversion': 'off',
      // n plugin rules for unresolved packages (viz.js)
      'n/no-missing-require': 'off',
      'import-x/newline-after-import': 'off',
      // Perfectionist sort rules
      'perfectionist/sort-heritage-clauses': 'off',
    },
    linterOptions: {
      reportUnusedDisableDirectives: false,
    },
  },
  {
    files: ['scripts/*.ts'],
    rules: {
      'no-console': 'off',
    },
  },
];
